### ISSUE TITLE
Latest JuliaHub page not available

### ISSUE THREAD

**Issue by schillic** [JuliaReach/RangeEnclosures.jl#183]
The standard link to JuliaHub

https://juliahub.com/ui/Packages/General/RangeEnclosures

does not work. The link to an earlier version

https://juliahub.com/ui/Packages/General/RangeEnclosures/0.2.2

still works. But there has not been any suspicious [change since then](https://github.com/JuliaReach/RangeEnclosures.jl/compare/v0.2.2...v0.2.3).

**Comment by lucaferranti** [comment]
Seems to work now, points to 0.2.5
