### ISSUE TITLE
Cannot run tests in Julia v1.12

### ISSUE THREAD

**Issue by schillic** [JuliaReach/RangeEnclosures.jl#195]
See the [PkgEval log](https://juliaci.github.io/NanosoldierReports/pkgeval_badges/R/RangeEnclosures.html).

The problem is that `CxxWrap` and `SDPA` fail to build. I tried to build them separately and that works. The reason is likely that an old version of `CxxWrap` (v0.14.2) is used in the tests, and that probably happens because some other test dependency holds the new version back.

I know that `AffineArithmetic` is blocking `Polynomials`, which may be the root cause. I had sent a request to bump the version in https://github.com/JuliaIntervals/AffineArithmetic.jl/pull/39 but nobody looked at it, so it seems we are stuck.
@lucaferranti, could you take a look at that PR?

**Comment by lucaferranti** [comment]
Yes I ll look at it tomorrow

**Comment by lucaferranti** [comment]
That was indeed pretty trivial MR, merged now. How is that related to SDPA and Cxxwrap though?

**Comment by schillic** [comment]
Honestly, it was a guess. But I just tried locally and now `SDPA` can be built!
Let us see what the next PkgEval run says...

**Comment by schillic** [comment]
Unfortunately, the problem seems to persist. Strange that I can build these packages locally in Julia v1.12 without a problem... This makes it hard to debug.

**Comment by schillic** [comment]
It is much simpler: `SDPA` alone also fails on PkgEval, and it is holding back `CxxWrap`. I asked them to fix that.
