### ISSUE TITLE
Release the package?

### ISSUE THREAD

**Issue by dpsanders** [JuliaReach/RangeEnclosures.jl#23]
This package does not seem to be `add`able using the Julia package manager (even though the README implies that it is).

**Comment by mforets** [comment]
True, it hasn't been released yet. Good idea, I'll do it asap.

**Comment by schillic** [comment]
Check list:
* [ ] install `Julia TagBot` and `JuliaTeam Registrator`
* [ ] resolve #24

**Comment by lucaferranti** [comment]
the tagbot file seems to be there, is it fine

**Comment by lucaferranti** [comment]
with a quick look, I don't see anything wrong at least

**Comment by schillic** [comment]
The release is officially triggered.
