### ISSUE TITLE
Package not installable on Windows

### ISSUE THREAD

**Issue by mforets** [JuliaReach/RangeEnclosures.jl#36]
SDPA is currently not installable on Windows (thanks @dfcaporale for pointing this out). Hence RangeEnclosures.jl cannot be used in that system. I suggest that we either let the `:SumOfSquares` backend be optional, or find another default SDP solver that works on Windows.

**Comment by mforets** [comment]
We should also add appveyor for testing on Windows.

**Comment by lucaferranti** [comment]
I think SDPA is now installable on windows? (but doesn't work on v1.7 or higher) see #65
