### ISSUE TITLE
use type dispatch for `enclose`

### ISSUE THREAD

**Issue by lucaferranti** [JuliaReach/RangeEnclosures.jl#64]
instead of having a bunch of if-else statements in the `enclose` function it might be nice to have  a type system for the enclosure algorithms and dispatch with those, something like

```julia
abstract type AbstractIntervalEnclosureAlgorithm end

struct BisectionEnclosure <: AbstractIntervalEnclosureAlgorithm
  max_steps::Int
  tol::Float64
end

struct OptimisationEnclosure <: ....
  ....
end
```

etc. etc. after that there are two design options

### Option 1

make the solvers functors, i.e. something like

```julia
function (be::BisectionEnclosure)(f::Function, X::Interval)
  for i in 1:be.max_steps
```

and the enclose is just (mutatis mutandis)

```julia
enclose(f::Function, X::Interval, solver::AbstractIntervalEnclosureAlgorithm=_default_solver()) = solver(f, X)
```

### Option 2

dispatch directly on enclose, i.e.

```julia
function enclose(f::Function, X::Interval, be::BisectionEnclosure)
  for i in be.max_steps
  ....
```

whether the difference between the two options is just stylistic or if there is some benchmark difference is not clear to me. fwiw, I use functors in IntervalLinearAlgebra, but mainly because the syntax seems more exoteric.... arguably not a good reason :)

**Comment by lucaferranti** [comment]
duplicate of #35 I guesss

**Comment by mforets** [comment]
I lean towards option 2. I think it makes composability cleaner, in the sense that an algorithm that needs an enclosure step can just call the function `enclose` with the given options, which can be passed from the top-level function. That said, I see it's nice to prototype with callable objects and we can have them, but maybe just like syntactic sugar,

```julia
function (be::BisectionEnclosure)(f::Function, X::Interval)
    encose(f, X, be)
...
```

**Comment by schillic** [comment]
I would suggest to make the algorithm the first argument. It is usually easiest to understand different methods if they dispatch on the first argument. And it allows to add more arguments with default values later without having to remember the index.

**Comment by mforets** [comment]
Not sure that having the algorithm as first argument plays well with having a default algorithm; for the first argument I would rather pass the function `f` whose range is to be enclosed. We can certainly have a two-level dispatch with an `_enclose` function which dispatches on the first argument -- we do this often, e.g. in `solve / `post` in RA or in `foo` / `_foo` in LazySets.

**Comment by mforets** [comment]
On a related note, we'd like to have to classes of algorithms: one for the optimization backend, and one for the search (that works on top of the optimization backend), I think it is reasonable to make them the 3rd and 4th arguments respectively.

**Comment by mforets** [comment]
Should we close this now? (https://github.com/JuliaReach/RangeEnclosures.jl/pull/72)

**Comment by lucaferranti** [comment]
I think so
