### ISSUE TITLE
HeapedVector not defined

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaReach/RangeEnclosures.jl#87]
This happened before I realized I had to include IntervalOptimisation.jl -- making that clearer in the docs would help.
README says _ are available, so either use them or let folks know they are available for use when the user "uses" them.

```
julia> f(x) = exp(x)
f (generic function with 1 method)

julia> dom = 0.0 .. 1/16
[0, 0.0625]

julia> enclose(f,dom,BranchAndBoundEnclosure())
[1, 1.0645]

julia> enclose(f,dom,RangeEnclosures.MooreSkelboeEnclosure())
ERROR: UndefVarError: HeapedVector not defined
```

**Comment by mforets** [comment]
Yep, we should make the README more clear and also check that the required packages are loaded when instantiating each method (such that `MooreSkelboeEnclosure()` returns an error that `IntervalOptimisation` needs to be loaded).

We've started with a [very small](https://github.com/JuliaReach/RangeEnclosures.jl/blob/master/Project.toml#L5) number of hard dependencies, but we can always review them as the package evolves.
